# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-08 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.CharField(max_length=50)),
                ('number2', models.CharField(max_length=50)),
            ],
        ),
    ]
