# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-08 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculator',
            old_name='number1',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='number2',
        ),
    ]
